name: Development

on:
  push:
    branches-ignore:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: go version
      - run: go mod tidy
      - run: make
